import NavBarWhite from './NavBar/page';
import SearchBar from './SearchBar/page';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NavBarWhite />
        <SearchBar />
        {children}
      </body>
    </html>
  )
}
