export const nodeStyle = [
  // Protein Coding nodes: Core (filled)
  {
    selector: 'node[type = "protein_coding"][Level = "Core"]',
    style: {
      shape: "round-rectangle",
      "background-color": "#ABD0F1",
      label: "data(name)",
      "font-size": "6px",
      "text-valign": "center",
      color: "#fff",
      width: "label",
      height: "label",
      padding: "5px",
      cursor: "pointer",
      "text-outline-width": 0,
      "text-outline-color": "#fff",
      "text-outline-opacity": 0,
    },
  },
  // Protein Coding nodes: Neighbor (transparent fill, colored border)
  {
    selector: 'node[type = "protein_coding"][Level = "Neighbor"]',
    style: {
      shape: "round-rectangle",
      "background-opacity": 0,
      "border-width": 2,
      "border-color": "#ABD0F1",
      label: "data(name)",
      "font-size": "6px",
      "text-valign": "center",
      color: "#333",
      width: "label",
      height: "label",
      padding: "5px",
      cursor: "pointer",
      "text-outline-width": 0,
      "text-outline-color": "#fff",
      "text-outline-opacity": 0,
    },
  },
  // SNP nodes: Core (filled)
  {
    selector: 'node[type = "SNP"][Level = "Core"]',
    style: {
      shape: "round-rectangle",
      "background-color": "#FFB77F",
      label: "data(id)",
      "font-size": "6px",
      "text-valign": "center",
      color: "#fff",
      width: "label",
      height: "label",
      padding: "5px",
      cursor: "pointer",
      "text-outline-width": 0,
      "text-outline-color": "#fff",
      "text-outline-opacity": 0,
    },
  },
  // SNP nodes: Neighbor (transparent fill, colored border)
  {
    selector: 'node[type = "SNP"][Level = "Neighbor"]',
    style: {
      shape: "round-rectangle",
      "background-opacity": 0,
      "border-width": 2,
      "border-color": "#FFB77F",
      label: "data(id)",
      "font-size": "6px",
      "text-valign": "center",
      color: "#333",
      width: "label",
      height: "label",
      padding: "5px",
      cursor: "pointer",
      "text-outline-width": 0,
      "text-outline-color": "#fff",
      "text-outline-opacity": 0,
    },
  },
  // Ontology nodes: Core (filled)
  {
    selector: 'node[type = "ontology"][Level = "Core"]',
    style: {
      shape: "round-rectangle",
      "background-color": "#B57E47",
      label: "data(id)",
      "font-size": "6px",
      "text-valign": "center",
      color: "#fff",
      width: "label",
      height: "label",
      padding: "5px",
      cursor: "pointer",
      "text-outline-width": 0,
      "text-outline-color": "#fff",
      "text-outline-opacity": 0,
    },
  },
  // Ontology nodes: Neighbor (transparent fill, colored border)
  {
    selector: 'node[type = "ontology"][Level = "Neighbor"]',
    style: {
      shape: "round-rectangle",
      "background-opacity": 0,
      "border-width": 2,
      "border-color": "#B57E47",
      label: "data(id)",
      "font-size": "6px",
      "text-valign": "center",
      color: "#333",
      width: "label",
      height: "label",
      padding: "5px",
      cursor: "pointer",
      "text-outline-width": 0,
      "text-outline-color": "#fff",
      "text-outline-opacity": 0,
    },
  },
  // Node active state
  {
    selector: "node:active",
    style: {
      "overlay-padding": "0px",
      "overlay-opacity": 0,
    },
  },
  // Edge style
  {
    selector: "edge",
    style: {
      width: 1,
      "line-color": "#d3d3d3",
      "target-arrow-color": "#545454",
      "target-arrow-shape": "vee",
      "arrow-scale": 0.8,
      "curve-style": "bezier",
    },
  },
];
